package banking;

/**
 *
 * @author DEEPTIRANJAN SWAIN
 */
public class balanceInquiry extends javax.swing.JFrame {
    Connection_Provider cp = new Connection_Provider();
    String cardno, pin;
    int balance = 0;
    
    public balanceInquiry(String cardno, String pin) {
        this.cardno = cardno;
        this.pin = pin;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        view_ = new javax.swing.JButton();
        balance_ = new javax.swing.JLabel();
        transaction_ = new javax.swing.JButton();
        exit_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        view_.setBackground(new java.awt.Color(0, 153, 0));
        view_.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        view_.setText("View Balance");
        view_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_ActionPerformed(evt);
            }
        });

        balance_.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        balance_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        transaction_.setBackground(new java.awt.Color(0, 204, 204));
        transaction_.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        transaction_.setText("Another Transaction");
        transaction_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaction_ActionPerformed(evt);
            }
        });

        exit_.setBackground(new java.awt.Color(255, 0, 0));
        exit_.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exit_.setText("Exit");
        exit_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(view_, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(balance_, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(transaction_, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exit_, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(view_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(balance_, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(transaction_, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(exit_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void view_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_ActionPerformed
        try {
            String q = "select balance from bank where cardno = ? and pin = ?";            
            java.sql.PreparedStatement ps = cp.conn.prepareStatement(q);
            
            ps.setString(1, cardno);
            ps.setString(2, pin);
            
            java.sql.ResultSet set = ps.executeQuery();
            
            
            while(set.next()){
                balance = set.getInt("balance");
                System.out.println(balance);
            }
            
            balance_.setText(Integer.toString(balance));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_view_ActionPerformed

    private void exit_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit_ActionPerformed

    private void transaction_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaction_ActionPerformed
        new transaction(cardno, pin).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_transaction_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(balanceInquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(balanceInquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(balanceInquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(balanceInquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new balanceInquiry("", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balance_;
    private javax.swing.JButton exit_;
    private javax.swing.JButton transaction_;
    private javax.swing.JButton view_;
    // End of variables declaration//GEN-END:variables
}
